Made a installer script for 3DashTools
cgytrus/ThreeDashTools pull request #1
Opened 2022-09-25 05:54 UTC by Hassunaama

This includes Bepinex, 6Dash and 3DashTools install.

2022-09-25 06:47 UTC, cgytrus commented
why does it need admin perms?

2022-09-25 06:49 UTC, Hassunaama commented
> why does it need admin perms?

It cannot run the Bepinex script without them because of windows policy's

2022-09-25 07:00 UTC, cgytrus requested changes

2022-09-25 07:00 UTC, cgytrus commented on 3DashTools-Install.bat
> +call powershell -command (new-object System.Net.WebClient).DownloadFile('https://github.com/cgytrus/SixDash/releases/download/v0.3.0/SixDash-0.3.0.zip', 'sixdash.zip') >nul
don't hardcode the versions, use the github api to get the latest version like in the bepinex installer script

2022-09-25 07:00 UTC, cgytrus commented on 3DashTools-Install.bat
> +call powershell -command (new-object System.Net.WebClient).DownloadFile('https://github.com/cgytrus/SixDash/releases/download/v0.3.0/SixDash-0.3.0.zip', 'sixdash.zip') >nul
same on line 32

2022-09-25 07:00 UTC, cgytrus commented on 3DashTools-Install.bat
> +if /i "%current_time%" GEQ " 5:00" if /i "%current_time%" LSS "13:00" echo Good morning %username%! Welcome to the 3DashTools Installer.
why is this even a thing in this script

2022-09-25 07:00 UTC, cgytrus commented on 3DashTools-Install.bat
> +echo.
copy-pasted code

2022-09-25 07:00 UTC, cgytrus commented on 3DashTools-Install.bat
> +echo Feel free to close this window.
the texts in this are generally weird

2022-09-25 07:00 UTC, cgytrus commented on 3DashTools-Install.bat
> +3Dash.exe
wouldnt do that

2022-09-25 07:02 UTC, cgytrus commented
generally i dont rly think its a good idea to have an installer script, it's better to put effort into adding 3dash support to [r2mm](https://github.com/ebkr/r2modmanPlus)

2022-09-25 07:09 UTC, cgytrus commented
the problem with that, however, is that it won't work unless the game is on a supported store, itch.io is not one of them
we'll probably have to work with ebkr to either add support for itch.io (which would actually require players to use the itch app to get the game), or add proper support for games from unsupported stores

2022-10-01 16:50 UTC, Hassunaama commented on 3DashTools-Install.bat
> +if /i "%current_time%" GEQ " 5:00" if /i "%current_time%" LSS "13:00" echo Good morning %username%! Welcome to the 3DashTools Installer.
Fixed?

2022-10-01 16:50 UTC, Hassunaama commented on 3DashTools-Install.bat
> +echo.
Fixed.

2022-10-01 16:51 UTC, Hassunaama commented on 3DashTools-Install.bat
> +echo Feel free to close this window.
Fixed.

2022-10-01 16:51 UTC, Hassunaama commented on 3DashTools-Install.bat
> +3Dash.exe
Fixed.

2022-10-01 17:02 UTC, cgytrus commented
noticed you made more changes
my comments still apply, i don't really want an installer script

2022-10-01 17:02 UTC, Hassunaama commented
> generally i dont rly think it's a good idea to have an installer script, it's better to put effort into adding 3dash support to [r2mm](https://github.com/ebkr/r2modmanPlus)

As you want.

2022-10-01 17:02 UTC, closed without merging